### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bre7** [bre7/gatsby-plugin-acknowledgements#1]
v1.0
- [ ] Output LICENSE info for each dependency (TXT format)

Format:
> **DEPENDENCY_NAME**
License: **LICENSE_NAME**
**LICENSE_URL**
**COPYRIGHT_FOOTER**

Future
- [ ] Flag to include devDependencies
- [ ] Output file as HTML (template formatting)
- [ ] Include other assets (e.g. images from Unsplash)
    - Require ASSETS.TXT or similar (`path` -> `LICENSE_URL`)

**Comment by bre7** [comment]
Useful resources:
* https://github.com/mwittig/npm-license-crawler
* https://stackoverflow.com/questions/16274841/output-all-licenses-of-installed-node-js-libraries
